In [1]:
import numpy as np   # importando a biblioteca de funções de python


In [3]:
#criar uma matriz unidimensional = array unidimencional
M = np.array([10, 24, 54, 78, 31])
M 

array([10, 24, 54, 78, 31])

In [4]:
type(M)

numpy.ndarray

In [5]:
print(M)

[10 24 54 78 31]


In [6]:
print("{}".format(M))

[10 24 54 78 31]


In [7]:
print("{}".format(M[2]))

54


In [8]:
print("{}".format(M[10]))

IndexError: index 10 is out of bounds for axis 0 with size 5

In [9]:
#O último elemento de parada [0:4] não imprimi 
print("{}".format(M[0:4]))

[10 24 54 78]


In [10]:
M

array([10, 24, 54, 78, 31])

In [11]:
print(M.shape)

(5,)


In [12]:
#array multidimensional 
MD = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])

In [13]:
print("{}".format(MD))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
MD.shape

(2, 6)

In [16]:
transp = MD.T  #Transpor um array
print(transp)   

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [17]:
transp.shape

(6, 2)

In [20]:
MD

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
MD[1,1]

8

In [21]:
MD[1][1]

8

In [22]:
MD.shape[0] # O parâmetro de entrada 0, permite ver a quantidade de linhas do array


2

In [23]:
MD.shape[1] # O parâmetro de entrada 1, permite ver a quantidade de colunas do array

6

In [24]:
#CRIAR UMA SUBMATRIZ 

#subMD recebe as linhas localizadas na posição zero e um. E colunas de zero a dois
subMD = MD[0:2, 0:3]

print("{}".format(subMD))

[[1 2 3]
 [7 8 9]]


In [27]:
#MODIFICAR ELEMENTROS DAS MATRIZES 

MD[1,1] = 11
print("{}".format(MD))


[[ 1  2  3  4  5  6]
 [ 7 11  9 10 11 12]]


In [ ]:
# TRANSFORMAR PARA NUMERO REAL
MR = np.array([[1.0, 2, 3, 4, 5, 6], [1000, 12, 32111, 788,1]], [6, 7, 8, 9, 1999]])


In [ ]:
print("{}".format(MR))
